name: E2E-PoC

on:
  schedule:
    - cron: '0 4 * * *'   # original trigger
  workflow_dispatch:       # manual trigger
  pull_request:            # <-- PoC: simulate dangerous misconfiguration

jobs:
  poc_demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ---- PoC malicious step ----
      - name: "[PoC] Simulate exfiltration on PR"
        if: github.event_name == 'pull_request'
        run: |
          echo ">>> This is a safe PoC simulation"
          echo ">>> In the real repo, secrets like RUNNER_REG_TOKEN and GCS_KEY would be exposed"
          echo "PoC executed at $(date)" >> proof.txt

      - name: Upload proof artifact
        uses: actions/upload-artifact@v3
        with:
          name: proof
          path: proof.txt
      # ----------------------------

  # keep an example of original jobs, but stripped of secrets
  dummy_update_vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dummy update
        run: echo "Simulating update_vm job (no secrets)"

